# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tdes 1.0.0 ruby lib
# stub: ext/tdes/extconf.rb

Gem::Specification.new do |s|
  s.name = "tdes".freeze
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Gabriel Bastos".freeze]
  s.date = "2022-06-24"
  s.description = "triple DES encryption implemented in C".freeze
  s.email = "gabriel.bastos@cloudwalk.io".freeze
  s.extensions = ["ext/tdes/extconf.rb".freeze]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "ext/tdes/extconf.rb",
    "ext/tdes/tdes.c",
    "ext/tdes/tdes_class.c",
    "ext/tdes/tdes_class.h",
    "lib/tdes.rb"
  ]
  s.homepage = "http://github.com/bbcoimbra/br-cnpj".freeze
  s.rubygems_version = "3.2.3".freeze
  s.summary = "triple DES encryption implemented in C".freeze
end

