# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: tdes 2.0.0 ruby lib
# stub: ext/tdes/extconf.rb

Gem::Specification.new do |s|
  s.name = "tdes".freeze
  s.version = "2.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Gabriel Bastos".freeze]
  s.date = "2022-07-06"
  s.description = "triple DES encryption implemented in C using openssl".freeze
  s.email = "gabriel.bastos@cloudwalk.io".freeze
  s.extensions = ["ext/tdes/extconf.rb".freeze]
  s.extra_rdoc_files = [
    "LICENSE"
  ]
  s.files = [
    "ext/tdes/extconf.rb",
    "ext/tdes/tdes.c",
    "ext/tdes/tdes_class.c",
    "ext/tdes/tdes_class.h",
    "lib/tdes.rb"
  ]
  s.homepage = "https://github.com/cloudwalk/ruby-3des".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.2.3".freeze
  s.summary = "triple DES encryption implemented in C".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to? :add_runtime_dependency then
    s.add_development_dependency(%q<rake-compiler>.freeze, [">= 0"])
    s.add_development_dependency(%q<jeweler>.freeze, [">= 0"])
  else
    s.add_dependency(%q<rake-compiler>.freeze, [">= 0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 0"])
  end
end

